apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-exam-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: manqo/jenkins-exam-app:latest # Wird von Jenkins überschrieben
        ports:
        - containerPort: 80
